### ISSUE TITLE
Yaml

### ISSUE THREAD

**Issue by twoodward** [JasonMillward/Autorippr#104]
I am having issues getting this working. Anytime I try to run the test I am receiving this message:

tylerwoodward@server:~/.autorippr$ python autorippr.py --test
Traceback (most recent call last):
  File "autorippr.py", line 55, in <module>
    import yaml
ImportError: No module named yaml

I have made sure to run sudo pip install tendo pyyaml peewee

**Comment by JasonMillward** [comment]
Can you run both `pip --version` and `python --version` to make sure the versions match. It's possible to run python3 and pip for python 2.7

    freyr :: ~ % pip --version
    pip 7.1.2 from /usr/local/lib/python2.7/dist-packages (python 2.7)
    freyr :: ~ % python --version
    Python 2.7.6

And just double check the packages were installed correctly using `pip list | egrep "(YAML|tendo|peewee)"`

    freyr :: ~ %  pip list | egrep "(YAML|tendo|peewee)"
    peewee (2.2.3)
    PyYAML (3.10)
    tendo (0.2.4)

**Comment by tonyrein** [comment]
I ran into something similar with another Python program. It turned out that the "missing" module had been installed by pip into the Python 3.5 directory structure, but the program that needed it was using Python 3.4. I don't know what your environment is, but you might check to see if you have more than one "sub-version" of Python 2.7 installed, and if so see where your modules are getting installed.

I solved it by explicitly telling pip to install for Python 3.4 instead of Python 3.5 by executing:
python3.4 /usr/bin/pip3 install <module name>.
