### ISSUE TITLE
Can it rip ISO and BDMV files?

### ISSUE THREAD

**Issue by phathak** [JasonMillward/Autorippr#112]
Hi!

This program looks awesome! I was wondering if it can rip ISO and BDMV files from the hard drive rather than from the optical drive. If not, are you planning to add this feature in the near future?

Thanks a lot!

Bruno

**Comment by JasonMillward** [comment]
If you took the time to mount those ISO files as a virtual disk then yes, this tool will handle them exactly like an optical drive. 

As for ripping BDMV files, it's not possible through this tool currently and probably won't be added since it was only designed to assist with the ripping/backup of physical CDs.
